server:
  servlet:
    context-path: /api/businessExample1/
  port: 8001


eureka:
  client:
    service-url:
      defaultZone: http://wwww.eureka-server.cn:7001/eureka/
    register-with-eureka: true


spring:
  application:
    name: business-example1

ribbon:
  eureka:
    enabled: true